### ISSUE TITLE
In search for a flatten option

### ISSUE THREAD

**Issue by dominikwilkowski** [alanshaw/grunt-include-replace#49]
Hey there,

I am looking to move from grunt-includes to you package but have come across one issue I may not be able to fix.
In grunt-includes you have a [`flatten` option](https://github.com/vanetix/grunt-includes#flatten) that ignores the folder structure of the processed HTML files and starts with that folder.
That way my folder with unprocessed HTML files can be rendered and go into a `PROD` folder.

I have my unprocessed files in `whatever/folder/index.html`
Currently I get `PROD/whatever/folder/index.html`
What I want is: `PROD/index.html`

and every respective file with folders so:
My unprocessed files in `whatever/folder/sub/index.html`
Currently I get `PROD/whatever/folder/sub/index.html`
What I want is: `PROD/sub/index.html`

What do you think?

**Comment by gorhgorh** [comment]
ha ha thanks for this issue, i was thinking i was not finding the flatten opt, mainly cause there isn't one :)

**Comment by alanshaw** [comment]
Does the flatten option not work?
http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by dominikwilkowski** [comment]
yeah thanks I didn't realise you had to have `expand: true,` set for this to work.
Cheers
