### ISSUE TITLE
Variable name shows up when not defined

### ISSUE THREAD

**Issue by dloewen** [alanshaw/grunt-include-replace#51]
Instead of showing the variable name in the processed page, it would be nice to output nothing when the variable is not defined.

For example, I have a header.html include that gets a `@@title` variable passed in on all pages except for the home page, but `@@title` shows up in the title tag since it's not defined.

The workaround is to define it and leave it blank like this: `@@include('header.html', {"title": ""})`, but it would be easier to leave that out.

**Comment by alanshaw** [comment]
Could you set a blank global? - https://github.com/alanshaw/grunt-include-replace#optionsglobals

**Comment by dloewen** [comment]
That works great, thanks @alanshaw!
