### ISSUE TITLE
Unexpected token error when trying to replace @@sample with html code

### ISSUE THREAD

**Issue by janh92** [alanshaw/grunt-include-replace#60]
I get an unexpected token error in terminal when trying the following:

```index.html:
...
@@include('components/nav.html', {"list-items": "<li><a href="#">home</a></li>"})
...```

nav.html
```...
<ul>@@list-items</ul>
...```

**Comment by alanshaw** [comment]
Error in your JSON there - you need to escape those quotes around the href attribute value.

**Comment by janh92** [comment]
What about the # character? Can I solve that with backslash too ?

**Comment by alanshaw** [comment]
I don't think that's a problem in a JSON string.

**Comment by janh92** [comment]
Thanks for your help, it works!
