### ISSUE TITLE
Flatten destination output

### ISSUE THREAD

**Issue by nikkwong** [alanshaw/grunt-include-replace#61]
Hi, 

Is it possible to flatten the output of the files in the dest folder? My templates are nested relative to the grunt file into something like /src/templates/index.html so by declaring 

dest: 'dist';

the output is

dist/src/templates/index.html, 

where i'd prefer

dist/index.html

Thanks.

**Comment by alanshaw** [comment]
You can use the `cwd` option for this: http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

**Comment by wizzyfx** [comment]
```
        includereplace: {
            development: {
                options: {},
                files: [
                    {
                        src: 'some/dir/*.html',
                        dest: 'targetdir/',
                        flatten: true,
                        expand:true
                    }
                ],
            }
        }
```
