### ISSUE TITLE
How to replace a file itself ?

### ISSUE THREAD

**Issue by NextSeason** [alanshaw/grunt-include-replace#65]
I wanna to execute includereplace to a dir, replace all files in the directory.
How to set options ?

**Comment by alanshaw** [comment]
If you want to replace all the files in the directory you'll probably want to use the [grunt-contrib-clean](https://github.com/gruntjs/grunt-contrib-clean) task to remove all the files prior to running grunt-include-replace. By default grunt-include-replace will overwrite files in your output directory.

Hope that helps.
