### ISSUE TITLE
Renaming Generated files

### ISSUE THREAD

**Issue by kuzeko** [alanshaw/grunt-include-replace#71]
Allow renames (suffix?) to generated files

possible expected behaviour
```

includereplace: {
      include: {
        options: {
          // Task-specific options go here.
          includesDir: './',
        },
        src:  ['*.html'],
        dest: 'app/',
        cwd:  'pages/',
        expand: true,
        rename: [{
               match: '.html',
               replacement: '-generated.html'
            }]
      }
    }
```
Will check for names containing the match pattern and rename them with the replacement string, as would do `str.replace(match, replacement)`

**Comment by alanshaw** [comment]
This is built into grunt: http://gruntjs.com/configuring-tasks#building-the-files-object-dynamically

Does that do what you need?

If not, I'd probably not add this to grunt-include-replace over simply using a [grunt plugin](https://www.npmjs.com/package/grunt-rename) to do it.

**Comment by kuzeko** [comment]
Sure, it almost cover my use cases, just I was looking for that renaming to happen only when the `grunt-include-replace` plugin  actually found something to replace/rewrite.

Anyway, thanks for the pointer.
